### ISSUE TITLE
FAQ about licensing in the doc seems wrong; license seems inadequate for source code

### ISSUE THREAD

**Issue by dumblob** [JonathanMEdwards/subtext10#1]
The doc explicitly states that this work will not be open source (which I translate as "will not be licensed under one of FSF or OSI approved licenses"). But this repository contains a license file (CC BY-SA 4) and some sources.

I for myself find your work quite interesting (I didn't try Subtext10 nor Subtext9 but I myself am researching in my free time dataflow-based programming for about 10 years now and I liked e.g. your approach showcased in https://vimeo.com/106073134 ).

Could you clarify how is (not) open sourcing of your work meant?

The reason why I'm asking is very simple - history shows that being open source under a permissive license (MIT, BSD and alikes) is one of the few requirements a language has to fulfill to become widespread. Another reason is, that CC BY-SA 4 is not recommended for source code, but rather for other things.

**Comment by JonathanMEdwards** [comment]
Thanks for your comment. This repo is a terminated research experiment. By request I put it up publicly, in the remote chance that someone might learn something from it. I tacked on a restrictive license because I suspect open source has become a force for conformity rather than invention. See my blog or twitter for discussion. If I ever come up with something actually useful I'll revisit the issue - till then a restrictive non-commercial license seems the safest way to preserve my options.

**Comment by dumblob** [comment]
>This repo is a terminated research experiment.

Didn't know that. Could you elaborate? After a quick look I couldn't find anything on your web nor twitter.

**Comment by JonathanMEdwards** [comment]
https://alarmingdevelopment.org/?p=1465

**Comment by dumblob** [comment]
Hm, admittedly I don't sense any notion of a "terminated research" in that post. Could you clarify?

Or do you devote your time to the "edit problem" for now and once you've "sufficiently solved (parts of) it" you'll come back to Subtext (maybe Subtext11 at that time :wink:) to incorporate results from the "edit problem" research?
